### PR TITLE
Article detail UI done

### PR DESCRIPTION
**Pull request by felindalubis**
Simulator Screen Shot - iPhone 12 - 2021-12-14 at 22 32 30
Adding:
- article detail view
- navigate from list article to detail
- navigation bar tint to white

### CODE REVIEW

**Comment by felindalubis** [comment]
eh tab bar di hide apa tidak guyss

**Comment by aurelianatasha** [comment]
di hide fell langsung dr storyboardnya ajaa

**Comment by alba26** [comment]
Tab barbya ilangin dl ya frl

**Comment by felindalubis** [comment]
Sudah fixed, mintol approve yaa

**Review by aurelianatasha — APPROVED** [review]
Article detail UI done #25

**Review by alba26 — APPROVED** [review]

**Pull request merged**
